markdown: redcarpet
pygments: true

# Serve command options

# Personal
name: The MAX
logo: images/the-max-logo.png
baseurl: /the-max
img_url: /images
client_img_url: /images/clients

links:
  - name: Us
    url: us
    desc: who we are
  - name: Services
    url: services
    desc: what we offer
  - name: Works
    url: works
    desc: what we've done
  - name: Clients
    url: clients
    desc:
  - name: Contact
    url: contact
    desc:

colors:
  - 00baf2
  - f58345
  - 4db848
  - ef4023
  - 00baf2

clients:
  - name: Yamaha Vietnam
    img: yamaha.png
  - name: DAF
    img: daf.png
  - name: Levi's
    img: levi.png
  - name: Piaggio Vietnam
    img: piaggio.png
  - name: VNPT
    img: vnpt.png
  - name: Abbott
    img: abbott.png
  - name: Vidamo
    img: vidamo.png

