markdown: redcarpet
pygments: true

# Serve command options

# Personal
name: The MAX

links:
  - name: Us
    url: /us/
    desc: who we are
  - name: Services
    url: /services/
    desc: what we offer
  - name: Works
    url: /works/
    desc: what we've done
  - name: Clients
    url: /clients/
    desc: people we have
  - name: Contact
    url: /contact/
    desc:
